[build]
  command = "npm run build"
  publish = ".next"
  # Pin a stable Node.js for Next.js 13 + Prisma
  [build.environment]
    NODE_VERSION = "20.11.1"
    NEXT_TELEMETRY_DISABLED = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs"