[build]
  command = "npm run build"
  publish = ".next"

  # Use a supported major Node.js version (Netlify recommends major versions)
  [build.environment]
    NODE_VERSION = "20"
    NEXT_TELEMETRY_DISABLED = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs"