name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HUSKY: 0
      NEXT_TELEMETRY_DISABLED: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install deps
        run: npm install --no-audit --no-fund --legacy-peer-deps

      - name: Prisma generate
        run: npx prisma generate

      - name: Type check
        run: npm run type-check

      - name: Build
        run: npm run build